apiVersion: template.openshift.io/v1
kind: Template
objects:
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      name: ${NAME}
      labels:
        cronjob: ${NAME}
        template: ${NAME}-cronjob
    spec:
      schedule: 0 10 * * *
      concurrencyPolicy: Forbid
      suspend: true
      jobTemplate:
        metadata:
          creationTimestamp: null
          labels:
            cronjob: ${NAME}
            template: ${NAME}-job
        spec:
          backoffLimit: 0
          template:
            metadata:
              creationTimestamp: null
              labels:
                cronjob: ${NAME}
                template: ${NAME}-job
            spec:
              containers:
                - terminationMessagePath: /dev/termination-log
                  name: ${NAME}-cronjob
                  imagePullPolicy: Always
                  terminationMessagePolicy: File
                  image: image-registry.openshift-image-registry.svc:5000/61d198-tools/${NAME}:latest
                  command:
                    - "/bin/bash"
                    - "-c"
                    - "npm start"
                  env:
                    - name: OPENSHIFT_AUTH_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: ${OPENSHIFT_SECRET}
                          key: ${OPENSHIFT_SECRET_KEY}
                    - name: DRY_RUN
                      value: ${DRY_RUN}
                    - name: NUM_RELEASES_TO_KEEP
                      value: ${NUM_RELEASES_TO_KEEP}
              restartPolicy: Never
              terminationGracePeriodSeconds: 30
              activeDeadlineSeconds: 1600
              dnsPolicy: ClusterFirst
              securityContext: {}
              schedulerName: default-scheduler
      successfulJobsHistoryLimit: 5
      failedJobsHistoryLimit: 2
parameters:
  - name: NAME
    required: true
    value: imagetag-pruner
  - name: OPENSHIFT_SECRET
    required: true
  - name: OPENSHIFT_SECRET_KEY
    required: true
  - name: DRY_RUN
    required: false
    value: "true"
  - name: NUM_RELEASES_TO_KEEP
    require: false
    value: "10"
