{{- if .Values.mariadb.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.mariadb.componentName }}
  labels:
    component: {{ .Values.mariadb.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.mariadb.componentName }}
      release: {{ .Release.Name }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: {{ .Values.mariadb.componentName }}
        release: {{ .Release.Name }}
    spec:      
      containers:
        - name: db
          image: {{ .Values.images.mariadb.name }}:{{ .Values.images.mariadb.tag }}
          imagePullPolicy: {{ .Values.mariadb.imagePullPolicy }}
          resources:
{{ toYaml .Values.mariadb.resources | indent 12 }}
          envFrom:
            - secretRef:
                name: {{ template "bcparks_mariadb_secret" . }}
          ports:
            - name: {{ .Values.mariadb.service.portName }}              
              containerPort: {{ .Values.mariadb.service.port }}
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - exec mysqladmin ping
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - exec mysqladmin ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ template "bcparks_mariadb_volume_claim" . }}
{{- end }}