{{- if .Values.mariadb.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "bcparks_mariadb_volume_claim" . }}
  labels:
    component: {{ .Values.mariadb.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .Values.mariadb.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mariadb.pvc.size }}
  storageClassName: {{ .Values.mariadb.pvc.storageClassName }}
{{- end }}