kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.maintenance.componentName }}
  labels:
    component: {{ .Values.maintenance.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.maintenance.componentName }}
      release: {{ .Release.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        component: {{ .Values.maintenance.componentName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.maintenance.componentName }}
          resources:
{{ toYaml .Values.maintenance.resources | indent 12 }}
          image: {{ .Values.images.maintenance.name }}:{{ .Values.images.maintenance.tag }}
          imagePullPolicy: {{ .Values.maintenance.imagePullPolicy }}
          ports:
            - name: {{ .Values.maintenance.service.portName }}
              containerPort: {{ .Values.maintenance.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3