{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-cms-secret" .Release.Name)) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cms-secret
  labels:
    component: {{ .Values.cms.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  STRAPI_API_TOKEN: {{ randAlphaNum 50 | quote }}
  STRAPI_API_USER_NAME: apiuser
  STRAPI_API_USER_EMAIL: api@{{ randAlphaNum 10 }}.com
  STRAPI_API_USER_PASSWORD: {{ randAlphaNum 50 | quote }}
  STRAPI_ADMIN_USER: admin
  STRAPI_ADMIN_PASSWORD: {{ randAlphaNum 50 | quote }}
  STRAPI_ADMIN_FIRST_NAME: Admin
  STRAPI_ADMIN_LAST_NAME: Account
  STRAPI_ADMIN_EMAIL: admin@{{ randAlphaNum 10 }}.com
  STRAPI_ADMIN_JWT_SECRET: {{ randAlphaNum 32 | quote }}
{{- end -}}