{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-cms-secret" .Release.Name)) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cms-secret
  labels:
    component: {{ .Values.cms.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  ADMIN_JWT_SECRET: {{ randAscii 16 | b64enc | quote }}
  APP_KEYS: {{ randAscii 16 | b64enc }},{{ randAscii 16 | b64enc }},{{ randAscii 16 | b64enc }},{{ randAscii 16 | b64enc }}
  API_TOKEN_SALT: {{ randAscii 16 | b64enc | quote }}
  JWT_SECRET: {{ randAscii 16 | b64enc | quote }}
  TRANSFER_TOKEN_SALT: {{ randAscii 16 | b64enc | quote }}
{{- end -}}