{{- $random_patroni_replication_password := randAlphaNum 32 }}
{{- $random_patroni_superuser_password := randAlphaNum 32 }}
{{- $random_patroni_app_user := randAlphaNum 10 }}
{{- $random_patroni_app_password := randAlphaNum 32 }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-patroni-secret" .Release.Name)) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "bcparks_patroni_fullname" . }}
    cluster-name: {{ template "bcparks_patroni_fullname" . }}
    component: {{ .Values.patroni.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "bcparks_patroni_fullname" . }}-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  replication-username: replication
  replication-password: {{ $random_patroni_replication_password | quote }}
  superuser-username: postgres
  superuser-password: {{ $random_patroni_superuser_password | quote }}
  app-db-name: {{ .Values.patroni.databaseName }}
  app-db-username: user_{{ $random_patroni_app_user }}
  app-db-password: {{ $random_patroni_app_password | quote }}
{{- end -}}