kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.public.componentName }}
  labels:
    component: {{ .Values.public.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.public.componentName }}
      release: {{ .Release.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        component: {{ .Values.public.componentName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.public.componentName }}
          resources:
{{ toYaml .Values.public.resources | indent 12 }}
          image: {{ .Values.images.public.name }}:{{ .Values.images.public.tag }}
          imagePullPolicy: {{ .Values.public.imagePullPolicy }}
          ports:
            - name: {{ .Values.public.service.portName }}
              containerPort: {{ .Values.public.service.port }}
              protocol: TCP