cluster:
  ssoAuthUrl: https://oidc.gov.bc.ca/auth

images:
  strapi:
    tag: prod
  staging:
    tag: prod
  admin:
    tag: prod
  public:
    tag: prod
  landing:
    tag: prod

cms:
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi

  env:
    externalUrl: https://cms.bcparks.ca

admin:
  env:
    externalUrl: https://staff.bcparks.ca

postgres:
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: 250m
      memory: 250Mi

  pvc:
    size: 20Gi

mariadb:
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: 250m
      memory: 250Mi

  pvc:
    size: 20Gi

patroni:
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi

  pvc:
    size: 10Gi

backup:
  enabled: true

  pvc:
    size: 10Gi

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [prod]
    name: 61d198-prod
