cluster:
  ssoAuthUrl: https://test.oidc.gov.bc.ca/auth

images:
  strapi:
    tag: test
  staging:
    tag: test
  admin:
    tag: test
  public:
    tag: test

cms:
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi

  env:
    externalUrl: https://test-cms.bcparks.ca

admin:
  env:
    externalUrl: https://test-staff.bcparks.ca

postgres:
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: 250m
      memory: 250Mi
  pvc:
    size: 20Gi

mariadb:
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: 250m
      memory: 250Mi
  pvc:
    size: 20Gi

patroni:
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi

  pvc:
    size: 10Gi

backup:
  enabled: true

  pvc:
    size: 10Gi

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [test]
    name: 61d198-test