cluster:
  ssoAuthUrl: https://loginproxy.gov.bc.ca/auth

images:
  strapi:
    tag: prod
  admin:
    tag: prod
  public:
    tag: prod
  maintenance:
    tag: prod

cms:
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 500Mi

  env:
    environment: prod
    externalUrl: https://cms.bcparks.ca

  hpa:
    minReplicas: 2
    maxReplicas: 4

admin:
  env:
    externalUrl: https://staff.bcparks.ca
    publicUrl: https://bcparks.ca

patroni:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi
  replicas: 3

  pvc:
    size: 10Gi

backup:
  enabled: true

  pvc:
    size: 10Gi

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [prod]
    name: 61d198-prod

public:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

  hpa:
    minReplicas: 2
    maxReplicas: 8
    memoryUtilizationThreshold: 60