cluster:
  ssoAuthUrl: https://test.loginproxy.gov.bc.ca/auth

images:
  strapi:
    tag: test
  admin:
    tag: test
  public:
    tag: test
  maintenance:
    tag: test

cms:
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi

  env:
    environment: test
    externalUrl: https://test-cms.bcparks.ca

  hpa:
    minReplicas: 1
    maxReplicas: 2

admin:
  env:
    externalUrl: https://test-staff.bcparks.ca

patroni:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi

  replicas: 1

  pvc:
    size: 10Gi

backup:
  enabled: true

  pvc:
    size: 10Gi

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [test]
    name: 61d198-test

public:
  hpa:
    minReplicas: 1
    maxReplicas: 2
