cluster:
  domain: apps.silver.devops.gov.bc.ca
  ssoAuthUrl: https://dev.oidc.gov.bc.ca/auth
  ssoRealm: g7v0xlf4
  ssoClientId: staff-portal

images:
  strapi:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/strapi
    tag: latest
  postgres:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/postgresql
    tag: "13"
  pgbouncer:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/pgbouncer
    tag: latest
  admin:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/admin
    tag: latest
  public:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/public
    tag: latest
  patroni:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/patroni-postgres
    tag: 2.0.1-12.4
  backup:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/backup-container
    tag: postgres-latest
  landing:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/landing
    tag: latest
  redis:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/redis
    tag: 6.2.6-alpine

cms:
  componentName: cms

  imagePullPolicy: Always

  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi

  env:
    nodeEnv: production
    databaseMinConnections: 0
    databaseMaxConnections: 10
    databaseIdleTimeout: 30000
    databaseCreateTimeout: 30000
    databaseAcquireTimeout: 30000
    smtpHost: apps.smtp.gov.bc.ca
    smtpPort: 25
    smtpFrom: noreply@gov.bc.ca
    smtpReplyTo: noreply@gov.bc.ca
    cacheEnabled: true
    cacheType: redis
    cacheModels: public-advisory,protected-area
    cacheTtl: 300000
    cacheTimeout: 10000

  service:
    portName: strapi
    port: 1337

  hpa:
    minReplicas: 1
    # Default to 1 max replica on dev, overriden in test and prod envs
    maxReplicas: 1

patroni:
  componentName: patroni

  enabled: true

  replicas: 3

  databaseName: cms

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 250Mi

  env:
    maxConnections: 240

  service:
    portName: patroni-leader
    port: 5432

  pvc:
    accessMode: ReadWriteOnce
    storageClassName: netapp-block-standard
    size: 1Gi

pgbouncer:
  enabled: true

  componentName: pgbouncer

  resources:
    limits:
      cpu: 150m
      memory: 150Mi
    requests:
      cpu: 50m
      memory: 50Mi

  env:
    defaultPoolSize: 80
    poolMode: transaction
    maxClientConn: 120

  service:
    portName: pgbouncer
    port: 6432

admin:
  imagePullPolicy: Always

  componentName: admin

  env:
    externalUrl: https://dev-staff.bcparks.ca
    statHolidayApi: https://canada-holidays.ca/api/v1/provinces/BC

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

  service:
    portName: admin
    port: 3000

public:
  imagePullPolicy: Always

  componentName: public

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

  service:
    portName: public
    port: 3000

  hpa:
    minReplicas: 1
    # Default to 1 max replica on dev, overriden in test and prod envs
    maxReplicas: 1

backup:
  componentName: postgres-backup

  # Disabled by default.  Overriden for TEST and PROD
  enabled: false

  pvc:
    accessMode: ReadWriteOnce
    storageClassName: netapp-file-backup
    size: 1Gi

  schedule: "0 9 * * *"

  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  backoffLimit: 0

  backupStrategy: "rolling"
  backupDir: "/backups/"

  retention:
    numBackups: 5
    dailyBackups: 7
    weeklyBackups: 4
    monthlyBackups: 1

  enironment:
    friendlyName: "bcparks.ca CMS Postgres Backup [dev]"
    name: "61d198-dev"

  tableSchema: "public"

  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 250Mi

landing:
  imagePullPolicy: Always

  componentName: landing

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

  service:
    portName: landing
    port: 3000


redis:
  imagePullPolicy: Always

  componentName: redis

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 64Mi

  service:
    portName: redis
    port: 6379