cluster:
  ssoAuthUrl: https://dev.loginproxy.gov.bc.ca/auth

images:
  strapi:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/strapi-develop
  admin:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/admin-develop
  public:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/public-develop
  maintenance:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/maintenance-develop
  etl:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/etl-develop
  elasticmanager:
    name: image-registry.openshift-image-registry.svc:5000/61d198-tools/elasticmanager-develop

cms:
  env:
    environment: alpha-dev
    externalUrl: https://alpha-dev-cms.bcparks.ca

admin:
  env:
    externalUrl: https://alpha-dev-staff.bcparks.ca
    publicUrl: https://alpha-dev.bcparks.ca

patroni:
  replicas: 1

backup:
  enabled: false

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [alpha-dev]

etl:
  #todo: this is temporarily true for debugging. change to false
  enabled: true
