cluster:
  ssoAuthUrl: https://test.loginproxy.gov.bc.ca/auth

images:
  strapi:
    tag: test
  admin:
    tag: test
  public:
    tag: test
  maintenance:
    tag: test
  etl:
    tag: test
  scheduler:
    tag: test

cms:
  env:
    environment: test
    externalUrl: https://test-cms.bcparks.ca

  hpa:
    maxReplicas: 2

admin:
  env:
    externalUrl: https://test-staff.bcparks.ca
    publicUrl: https://test.bcparks.ca

patroni:
  replicas: 1

  pvc:
    size: 5Gi

backup:
  enabled: true

  pvc:
    size: 10Gi

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [test]
    name: 61d198-test

public:
  hpa:
    maxReplicas: 2

scheduler:
  env:
    emailEnabled: true
