cluster:
  ssoAuthUrl: https://loginproxy.gov.bc.ca/auth

images:
  strapi:
    tag: prod
  admin:
    tag: prod
  public:
    tag: prod
  maintenance:
    tag: prod
  etl:
    tag: prod
  elasticmanager:
    tag: prod

cms:
  resources:
    limits:
      cpu: 650m
      memory: 1250Mi
    requests:
      cpu: 125m
      memory: 625Mi

  env:
    environment: prod
    externalUrl: https://cms.bcparks.ca
    cacheTtl: "600000"

  hpa:
    minReplicas: 2
    maxReplicas: 4
    cpuUtilizationThreshold: 65
    memoryUtilizationThreshold: 100

admin:
  env:
    externalUrl: https://staff.bcparks.ca
    publicUrl: https://bcparks.ca

patroni:
  resources:
    limits:
      cpu: 750m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
  replicas: 3

  pvc:
    size: 10Gi

backup:
  enabled: true

  pvc:
    size: 10Gi

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [prod]
    name: 61d198-prod

public:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

  hpa:
    minReplicas: 2
    maxReplicas: 8
    cpuUtilizationThreshold: 35
    memoryUtilizationThreshold: 85

etl:
  env:
    parkNamesApi: https://data.bcparks.ca/api/parks/names?status=established
