cluster:
  ssoAuthUrl: https://test.loginproxy.gov.bc.ca/auth

images:
  strapi:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/strapi-develop
    tag: test
  admin:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/admin-develop
    tag: test
  public:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/public-develop
    tag: test
  maintenance:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/maintenance-develop
    tag: test
  etl:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/etl-develop
    tag: test
  scheduler:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/scheduler-develop
    tag: test

cms:
  env:
    environment: alpha-test
    externalUrl: https://alpha-test-cms.bcparks.ca

  hpa:
    minReplicas: 1
    maxReplicas: 1

admin:
  env:
    externalUrl: https://alpha-test-staff.bcparks.ca
    publicUrl: https://alpha-test.bcparks.ca

patroni:
  replicas: 1

  pvc:
    size: 10Gi

backup:
  enabled: true

  pvc:
    size: 10Gi

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [alpha-test]
    name: c1643c-test

public:
  hpa:
    minReplicas: 1
    maxReplicas: 1

etl:
  enabled: true

scheduler:
  env:
    emailEnabled: true
    emailRecipient: manuji@oxd.com,mike@oxd.com
