cluster:
  ssoAuthUrl: https://oidc.gov.bc.ca/auth

images:
  strapi:
    tag: prod
  admin:
    tag: prod
  public:
    tag: prod
  landing:
    tag: prod

cms:
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 500Mi

  env:
    externalUrl: https://cms.bcparks.ca

  hpa:
    minReplicas: 2
    maxReplicas: 4

admin:
  env:
    externalUrl: https://staff.bcparks.ca

patroni:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 250Mi

  pvc:
    size: 10Gi

backup:
  enabled: true

  pvc:
    size: 10Gi

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [prod]
    name: 61d198-prod

public:
  hpa:
    minReplicas: 2
    maxReplicas: 4