apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "bcparks_patroni_fullname" . }}
    cluster-name: {{ template "bcparks_patroni_fullname" . }}
    component: {{ .Values.patroni.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  name: {{ template "bcparks_patroni_fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "bcparks_patroni_fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "bcparks_patroni_fullname" . }}
