kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.cms.componentName }}
  labels:
    component: {{ .Values.cms.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      component: {{ .Values.cms.componentName }}
      release: {{ .Release.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        component: {{ .Values.cms.componentName }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        {{- if .Values.mariadb.enabled }}
        - name: wait-for-mariadb
          image: {{ .Values.images.mariadb.name }}:{{ .Values.images.mariadb.tag }}        
          command: ['sh', '-c', 'until mysqladmin ping -h {{ template "bcparks_mariadb_fullname" . }} -u root -p"$MYSQL_ROOT_PASSWORD"; do echo waiting for database; sleep 2; done;']
          envFrom:
            - secretRef:
                name: {{ template "bcparks_mariadb_secret" . }}
        {{- else }}
        - name: wait-for-postgres
          image: {{ .Values.images.postgres.name }}:{{ .Values.images.postgres.tag }}
        {{- if .Values.pgbouncer.enabled }}
          command: ['sh', '-c', 'until pg_isready -h {{ template "bcparks_pgbouncer_fullname" . }} -p {{ .Values.pgbouncer.service.port }}; do echo waiting for database; sleep 2; done;']
        {{- else }}
          command: ['sh', '-c', 'until pg_isready -h {{ template "bcparks_patroni_fullname" . }} -p {{ .Values.patroni.service.port }}; do echo waiting for database; sleep 2; done;']
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Values.cms.componentName }}
          resources:
{{ toYaml .Values.cms.resources | indent 12 }}
          image: {{ .Values.images.strapi.name }}:{{ .Values.images.strapi.tag }}
          imagePullPolicy: {{ .Values.cms.imagePullPolicy }}
          ports:
            - name: {{ .Values.cms.service.portName }}
              containerPort: {{ .Values.cms.service.port }}
              protocol: TCP
          env:            
            - name: NODE_ENV
              value: {{ .Values.cms.env.nodeEnv }}
            - name: STRAPI_TELEMETRY_DISABLED
              value: "true"
            - name: STRAPI_SSO_AUTH_URL
              value: {{ .Values.cluster.ssoAuthUrl }}
            - name: STRAPI_SSO_REALM
              value: {{ .Values.cluster.ssoRealm }}
            - name: STRAPI_EXTERNAL_URL
            {{- if .Values.cms.env.externalUrl }}
              value: {{ .Values.cms.env.externalUrl }}
            {{- else }}
              value: {{ template "bcparks_cms_external_url" . }}
            {{- end }}
            - name: DATABASE_CLIENT
              value: {{ ternary "mysql" "postgres" .Values.mariadb.enabled }}
            - name: DATABASE_HOST
            {{- if .Values.mariadb.enabled }}
              value: {{ template "bcparks_mariadb_fullname" . }} 
            {{- else if .Values.pgbouncer.enabled }}
              value: {{ template "bcparks_pgbouncer_fullname" . }} 
            {{- else }}
              value: {{ template "bcparks_patroni_fullname" . }}
            {{- end }}
            - name: DATABASE_PORT
            {{- if .Values.mariadb.enabled }}
              value: {{ .Values.mariadb.service.port | quote }}
            {{- else if .Values.pgbouncer.enabled }}
              value: {{ .Values.pgbouncer.service.port | quote }}
            {{- else }}
              value: {{ .Values.patroni.service.port | quote }}
            {{- end }}              
            - name: DATABASE_USERNAME
            {{- if .Values.mariadb.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_mariadb_secret" . }}
                  key: MYSQL_USER
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-username
            {{- end }}
            - name: DATABASE_PASSWORD
            {{- if .Values.mariadb.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_mariadb_secret" . }}
                  key: MYSQL_PASSWORD
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-password
            {{- end }}
            - name: DATABASE_NAME
            {{- if .Values.mariadb.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_mariadb_secret" . }}
                  key: MYSQL_DATABASE
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "bcparks_patroni_secret" . }}
                  key: app-db-name
            {{- end }}
            - name: DATABASE_SSL
              value: "false"
            - name: DATABASE_MIN_CONNECTIONS
              value: {{ .Values.cms.env.databaseMinConnections | quote }}
            - name: DATABASE_MAX_CONNECTIONS
              value: {{ .Values.cms.env.databaseMaxConnections | quote }}
            - name: DATABASE_IDLE_TIMEOUT
              value: {{ .Values.cms.env.databaseIdleTimeout | quote }}
            - name: DATABASE_CREATE_TIMEOUT
              value: {{ .Values.cms.env.databaseCreateTimeout | quote }}
            - name: DATABASE_ACQUIRE_TIMEOUT
              value: {{ .Values.cms.env.databaseAcquireTimeout | quote }}
            - name: STRAPI_SMTP_HOST
              value: {{ .Values.cms.env.smtpHost }}
            - name: STRAPI_SMTP_PORT
              value: {{ .Values.cms.env.smtpPort | quote }}
            - name: STRAPI_SMTP_FROM
              value: {{ .Values.cms.env.smtpFrom }}
            - name: STRAPI_SMTP_REPLY_TO
              value: {{ .Values.cms.env.smtpReplyTo }}
          envFrom:
            - secretRef:
                name: {{ template "bcparks_cms_secret" . }}
            - secretRef:
                name: bcparks-object-storage
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.cms.service.portName }}
            initialDelaySeconds: 10
            timeoutSeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 20
        {{- if .Values.cms.pvc.enabled }}
          volumeMounts:
            - name: cms-data
              mountPath: /opt/app-root/src/public/uploads
        {{- end }}
    {{- if .Values.cms.pvc.enabled }}
      volumes:
        - name: cms-data
          persistentVolumeClaim:
            claimName: {{ template "bcparks_cms_volume_claim" . }}
    {{- end }}
