name: Build Staging on main branch

on:
  push:
    branches:
      - main
    paths:
      - src/staging/**

env:
  IMAGE_NAME: staging
  DEPLOYMENT_NAME: staging
  BUILDER_IMAGE: registry.access.redhat.com/ubi8/nodejs-14:1-43

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set vars
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login to OpenShift Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}
      - name: s2i Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: "src/staging"
          builder_image: ${{ env.BUILDER_IMAGE }}
          image: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_LICENSE_PLATE }}-tools/${{ env.IMAGE_NAME }}
          tags: latest ${{ steps.vars.outputs.sha_short }}
      - name: Push Docker image
        run: |
          docker push ${{ steps.build_image.outputs.image }}:latest
          docker push ${{ steps.build_image.outputs.image }}:${{ steps.vars.outputs.sha_short }}
      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_SERVICE_TOKEN }}
      - name: Deploy
        run: |
          oc -n ${{ secrets.OPENSHIFT_LICENSE_PLATE }}-dev set image deployment/bcparks-${{ env.DEPLOYMENT_NAME }} \
          ${{ env.DEPLOYMENT_NAME }}=${{ steps.build_image.outputs.image }}:${{ steps.vars.outputs.sha_short }} --record