name: Build Admin on main branch

on:
  push:
    branches:
      - main
    paths:
      - src/admin/**

env:
  IMAGE_NAME: admin
  DEPLOYMENT_NAME: admin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set vars
        id: vars
        run: echo "::set-output name=registry_image::${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_LICENSE_PLATE }}-tools/${{ env.IMAGE_NAME }}"

      - name: Login to OpenShift Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build
        run: |
          npm install
          npm run build
          docker build -t ${{ env.IMAGE_NAME }} .
          docker tag ${{ env.IMAGE_NAME }} ${{ steps.vars.outputs.registry_image }}:latest
        working-directory: src/admin

      - name: Push Docker image
        run: |
          docker push ${{ steps.vars.outputs.registry_image }}:latest

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_SERVICE_TOKEN }}

      - name: Trigger rollout
        run: |
          oc -n ${{ secrets.OPENSHIFT_LICENSE_PLATE }}-dev rollout restart deployment bcparks-${{ env.DEPLOYMENT_NAME }}
