name: Build Public builder on main branch

on:
  push:
    branches:
      - main
    paths:
      - src/staging/**

env:
  IMAGE_NAME: public-builder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set vars
        id: vars
        run: |
          echo "::set-output name=registry_image::${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_LICENSE_PLATE }}-tools/${{ env.IMAGE_NAME }}"

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Login to OpenShift Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push builder image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} -f Builder.Dockerfile .
          docker tag ${{ env.IMAGE_NAME }} ${{ steps.vars.outputs.registry_image }}:latest
          docker push ${{ steps.vars.outputs.registry_image }}:latest
        working-directory: src/staging

      - name: Trigger Gatsby static build workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-public
