name: Deploy to Test

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+-rc*"

env:
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_LICENSE_PLATE }}-tools
  ENVIRONMENT: test
  NAMESPACE: ${{ secrets.OPENSHIFT_LICENSE_PLATE }}-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_SERVICE_TOKEN }}
          
      - name: Backup images
        run: |
          oc -n ${{ env.TOOLS_NAMESPACE }} tag admin:${{ env.ENVIRONMENT }} admin:${{ env.ENVIRONMENT }}-backup-$(date +%s)
          oc -n ${{ env.TOOLS_NAMESPACE }} tag public-builder:${{ env.ENVIRONMENT }} public-builder:${{ env.ENVIRONMENT }}-backup-$(date +%s)
          oc -n ${{ env.TOOLS_NAMESPACE }} tag public:${{ env.ENVIRONMENT }} public:${{ env.ENVIRONMENT }}-backup-$(date +%s)
          oc -n ${{ env.TOOLS_NAMESPACE }} tag strapi:${{ env.ENVIRONMENT }} strapi:${{ env.ENVIRONMENT }}-backup-$(date +%s)

      - name: Trigger Gatsby static build workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-public
          client-payload: '{"env": "${{ env.ENVIRONMENT }}"}'

      - name: Trigger new rollout
        run: |
          oc -n ${{ env.NAMESPACE }} rollout restart deployment bcparks-admin
          oc -n ${{ env.NAMESPACE }} rollout restart deployment bcparks-cms