{{- if .Values.sysdig.enabled }}
apiVersion: ops.gov.bc.ca/v1alpha1
kind: SysdigTeam
metadata:
  name: 61d198-sysdigteam
  namespace: 61d198-tools
spec:
  team:
    description: {{ .Values.sysdig.description }}
    users:
    {{- range $users := .Values.sysdig.users }}   
    - name: {{ $users.email }}
      role: {{ $users.role | default "ROLE_TEAM_STANDARD" }}
    {{- end }}                                                                               
{{- end }}